Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'greet'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'greet' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 338, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/actions/action.py", line 305, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'greet' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'greet'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'greet' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 338, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/actions/action.py", line 305, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'greet' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/six/nlu/intent_classifier_tensorflow_embedding.ckpt
C:\Users\Jordan\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, OPTIONS, GET             /static/[filename]
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hello' with intent '{'name': 'greeting', 'confidence': 0.968995213508606}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	date: None
	dr: None
	medicine: None
	message: None
Current tracker state [None, {}, {'intent_greeting': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '11'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hello, welcome to the health portal!, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{}, {'intent_greeting': 1.0, 'prev_action_listen': 1.0}, {'intent_greeting': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'send a message' with intent '{'name': 'message_dr', 'confidence': 0.9115555882453918}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	date: None
	dr: None
	medicine: None
	message: None
Current tracker state [{'intent_greeting': 1.0, 'prev_action_listen': 1.0}, {'intent_greeting': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_message_dr': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_which_dr' with prob 0.83.
Action 'utter_ask_which_dr' ended with events '[]'
Bot utterance 'BotUttered(text: Ok, who's your doctor?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'intent_greeting': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_message_dr': 1.0}, {'prev_utter_ask_which_dr': 1.0, 'intent_message_dr': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'Dr. Barker' with intent '{'name': 'confirm_dr', 'confidence': 0.95320725440979}' and entities '[{'start': 0, 'end': 10, 'value': 'Dr Barker', 'entity': 'dr', 'confidence': 0.9922164532071696, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 11 events
Current slot values: 
	date: None
	dr: Dr Barker
	medicine: None
	message: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_message_dr': 1.0}, {'prev_utter_ask_which_dr': 1.0, 'intent_message_dr': 1.0}, {'entity_dr': 1.0, 'prev_action_listen': 1.0, 'intent_confirm_dr': 1.0, 'slot_dr_0': 1.0}]
There is a memorised next action '6'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_message' with prob 1.00.
Action 'utter_ask_message' ended with events '[]'
Bot utterance 'BotUttered(text: what would you like to ask the doctor?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_utter_ask_which_dr': 1.0, 'intent_message_dr': 1.0}, {'entity_dr': 1.0, 'prev_action_listen': 1.0, 'intent_confirm_dr': 1.0, 'slot_dr_0': 1.0}, {'entity_dr': 1.0, 'prev_utter_ask_message': 1.0, 'intent_confirm_dr': 1.0, 'slot_dr_0': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'My medicine is giving me cramps' with intent '{'name': 'request_refill', 'confidence': 0.6902287006378174}' and entities '[]'
Logged UserUtterance - tracker now has 15 events
Current slot values: 
	date: None
	dr: Dr Barker
	medicine: None
	message: None
Current tracker state [{'entity_dr': 1.0, 'prev_action_listen': 1.0, 'intent_confirm_dr': 1.0, 'slot_dr_0': 1.0}, {'entity_dr': 1.0, 'prev_utter_ask_message': 1.0, 'intent_confirm_dr': 1.0, 'slot_dr_0': 1.0}, {'intent_request_refill': 1.0, 'prev_action_listen': 1.0, 'slot_dr_0': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_confirmed_message' with prob 0.95.
Couldn't create message for template 'utter_confirmed_message'.
Action 'utter_confirmed_message' ended with events '[]'
Current tracker state [{'entity_dr': 1.0, 'prev_utter_ask_message': 1.0, 'intent_confirm_dr': 1.0, 'slot_dr_0': 1.0}, {'intent_request_refill': 1.0, 'prev_action_listen': 1.0, 'slot_dr_0': 1.0}, {'prev_utter_confirmed_message': 1.0, 'intent_request_refill': 1.0, 'slot_dr_0': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
